from app.models.mto import DrawingMeta, MTOItem, Summary, MTOResponse

def generate_mock_mto() -> MTOResponse:
    return MTOResponse(
        drawing_meta=DrawingMeta(
            drawing_no="ISO-1501-01",
            revision="2",
            line_number='6"-P-1501-A1A-IH',
            nps='6"',
            material_class="A1A",
            service="Process",
        ),
        items=[
            MTOItem(
                item_no=1,
                category="PIPE",
                description="Pipe, Seamless, BE, ASME B36.10",
                size_nps='6"',
                schedule_rating="SCH40",
                material_spec="ASTM A106 Gr.B",
                end_type="BW",
                quantity=1,
                unit="M",
                length_m=12.45,
                confidence=0.97,
            ),
            MTOItem(
                item_no=2,
                category="FITTING",
                description="90° LR Elbow, BW, ASME B16.9",
                size_nps='6"',
                schedule_rating="SCH40",
                material_spec="ASTM A234 WPB",
                end_type="BW",
                quantity=4,
                unit="EA",
                confidence=0.93,
            ),
            MTOItem(
                item_no=3,
                category="FLANGE",
                description="Weld Neck Flange, CL150, RF, ASME B16.5",
                size_nps='6"',
                schedule_rating="CL150",
                material_spec="ASTM A105",
                end_type="FLGD",
                quantity=2,
                unit="EA",
                confidence=0.91,
            ),
            MTOItem(
                item_no=4,
                category="VALVE",
                description="Gate Valve, CL150, RF, ASME B16.10",
                size_nps='6"',
                schedule_rating="CL150",
                material_spec="ASTM A216 WCB",
                end_type="FLGD",
                quantity=1,
                unit="EA",
                confidence=0.89,
            ),
            MTOItem(
                item_no=5,
                category="GASKET",
                description="Spiral Wound Gasket, 6 inch, CL150",
                size_nps='6"',
                schedule_rating="CL150",
                material_spec="SS316/Graphite",
                end_type="FLGD",
                quantity=2,
                unit="EA",
                confidence=0.95,
            ),
            MTOItem(
                item_no=6,
                category="BOLT",
                description="Stud Bolt Set, ASTM A193 B7 / A194 2H",
                size_nps='6"',
                schedule_rating="CL150",
                material_spec="A193 B7",
                end_type="FLGD",
                quantity=2,
                unit="SET",
                confidence=0.95,
            ),
        ],
        summary=Summary(
            total_pipe_length_m=12.45,
            fittings=4,
            flanges=2,
            valves=1,
            gaskets=2,
            bolt_sets=2,
            field_welds=1,
        ),
    )